// Make -> bare model name lists, and per-model trim (finition) name lists for a subset of
// makes. Model names below are bare (no make prefix); the seed script prefixes them.

export const CATALOG_MAKES: Record<string, string[]> = {
  AUDI: [
    '100', '200', '80', '90', 'A1', 'A2', 'A3', 'A4', 'A4 Allroad', 'A5', 'A6', 'A6 Allroad',
    'A7', 'A8', 'Cabriolet', 'Coupé', 'Q2', 'Q3', 'Q4', 'Q5', 'Q6', 'Q7', 'Q8', 'Q9', 'Quattro',
    'R8', 'RS Q3', 'RS Q8', 'RS2', 'RS3', 'RS4', 'RS5', 'RS6', 'RS7', 'S1', 'S2', 'S3', 'S4',
    'S5', 'S6', 'S7', 'S8', 'SQ2', 'SQ5', 'SQ6', 'SQ7', 'SQ8', 'TT', 'TT RS', 'TTS', 'V8',
    'e-tron', 'e-tron GT', 'Autre',
  ],
  BMW: [
    '1500 à 2000', '1M', '2002', 'C/CS/CSL', 'Isetta', 'M2', 'M3', 'M4', 'M5', 'M6', 'M8',
    'Série 1', 'Série 2', 'Série 3', 'Série 4', 'Série 5', 'Série 6', 'Série 7', 'Série 8',
    'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'XM', 'Z1', 'Z3', 'Z4', 'Z8', 'i3', 'i4', 'i5',
    'i7', 'i8', 'iX', 'iX1', 'iX2', 'iX3', 'Autre',
  ],
  CITROEN: [
    '2 CV', 'AX', 'Ami', 'Axel', 'BX', 'Berlingo', 'C-Crosser', 'C-Elysée', 'C-Zéro', 'C1',
    'C15', 'C2', 'C25', 'C3', 'C3 Aircross', 'C3 Picasso', 'C3 Pluriel', 'C4', 'C4 Aircross',
    'C4 Cactus', 'C4 Picasso', 'C4 SpaceTourer', 'C4 X', 'C5', 'C5 Aircross', 'C5 X', 'C6',
    'C8', 'CX', 'DS', 'DS3', 'DS4', 'DS4 Crossback', 'DS5', 'Dyane', 'Evasion', 'GS/GSA',
    'Holidays', 'Jumper', 'Jumpy', 'LN/LNA', 'Méhari', 'Nemo', 'SM', 'Saxo', 'SpaceTourer',
    'Traction/15', 'Visa', 'XM', 'Xantia', 'Xsara', 'Xsara Picasso', 'ZX', 'e-Mehari', 'Autre',
  ],
  FIAT: [
    '124', '124 Spider', '126', '127', '130', '131', '500', '500C', '500L', '500L Living',
    '500L Wagon', '500X', '600', '850', '900', 'Albea', 'Barchetta', 'Brava', 'Bravo',
    'Cinquecento', 'Coupe', 'Croma', 'Dino', 'Doblo', 'Ducato', 'Fiorino', 'Fiorino Qubo',
    'Freemont', 'Fullback', 'Grande Punto', 'Idea', 'Linea', 'Marea', 'Multipla', 'Palio',
    'Panda', 'Punto', 'Punto Evo', 'Regata', 'Ritmo', 'Scudo', 'Sedici', 'Seicento',
    'Spider Europa', 'Stilo', 'Strada', 'Talento', 'Tempra', 'Tipo', 'Topolino', 'Ulysse',
    'Uno', 'X1/9 Bertone', 'Autre',
  ],
  FORD: [
    'Aerostar', 'Anglia', 'B-MAX', 'Bronco', 'C-MAX', 'Capri', 'Cougar', 'Courrier', 'Crestline',
    'Crown', 'Custom', 'Customline', 'EcoSport', 'Econoline', 'Econovan', 'Edge', 'Elite',
    'Escape', 'Escort', 'Excursion', 'Expedition', 'Explorer', 'Express', 'F 100', 'F 150',
    'F 250', 'F 350', 'Fairlane', 'Fairlane Torino', 'Falcon', 'Falcon Futura', 'Fiesta', 'Flex',
    'Focus', 'Fusion', 'Futura', 'GT', 'Galaxie', 'Galaxy', 'Gran Torino', 'Granada',
    'Grand C-Max', 'Ka', 'Ka+', 'Kuga', 'LTD', 'Mainline', 'Maverick', 'Mercury', 'Model T',
    'Modèle 300', 'Mondeo', 'Mustang', 'Mustang Mach-E', 'Orion', 'Pinto', 'Probe', 'Puma',
    'Ranger', 'Raptor', 'S-MAX', 'Scorpio', 'Sierra', 'Sportka', 'Station Wagon', 'Streetka',
    'Taunus', 'Taurus', 'Thunderbird', 'Torino', 'Tourneo', 'Tourneo Connect', 'Tourneo Courier',
    'Transit', 'Transit 2T', 'Transit CustomCamper', 'Windstar', 'Autre',
  ],
  'MERCEDES-BENZ': [
    '180', '190', '200', '220', '230', '240', '250', '260', '270', '280', '290', '300', '320',
    '350', '380', '400', '416', '420', '450', '500', '560', '600', 'AMG GT', 'CE', 'CL', 'CLE',
    'Citan', 'Classe A', 'Classe B', 'Classe C', 'Classe CLA', 'Classe CLC', 'Classe CLK',
    'Classe CLS', 'Classe E', 'Classe G', 'Classe GL', 'Classe GLA', 'Classe GLB', 'Classe GLC',
    'Classe GLE', 'Classe GLK', 'Classe GLS', 'Classe M/ML', 'Classe R', 'Classe S', 'Classe SL',
    'Classe SLC', 'Classe SLK', 'Classe T', 'Classe V', 'Classe X', 'EQA', 'EQB', 'EQC', 'EQE',
    'EQE SUV', 'EQG', 'EQS', 'EQS SUV', 'EQT', 'EQV', 'MB 100', 'Marco Polo', 'SLR', 'SLS AMG',
    'Sprinter', 'Stuttgart', 'Vaneo', 'Vario', 'Viano', 'Vito', 'Autre',
  ],
  MINI: ['Aceman', 'Clubman', 'Clubvan', 'Cooper', 'Countryman', 'Mini', 'One', 'Paceman', 'Autre'],
  NISSAN: [
    '100NX', '200SX', '240 SX', '280 ZX', '300ZX', '350Z', '370Z', 'Almera', 'Almera Tino',
    'Altima', 'Ariya', 'Bluebird', 'Cabstar', 'Cargo', 'Cherry', 'Cube', 'Cédric', 'Evalia',
    'Frontier', 'GT-R', 'Interstar', 'Juke', 'King Cab', 'Kubistar', 'Laurel', 'Leaf', 'Maxima',
    'Micra', 'Murano', 'NP300', 'NV200', 'NV250', 'NV300', 'NV400', 'Navara', 'Note', 'Pathfinder',
    'Patrol', 'Pick-up', 'Pixo', 'Primastar', 'Primera', 'Pulsar', 'Qashqai', 'Qashqai+2', 'Quest',
    'Sentra', 'Serena', 'Silvia', 'Skyline', 'Stanza', 'Sunny', 'Terrano', 'Tilda', 'Titan',
    'Townstar', 'Trade', 'Urvan', 'Vanette', 'X-Trail', 'Autre',
  ],
  OPEL: [
    'Adam', 'Admiral', 'Agila', 'Ampera', 'Ampera-e', 'Antara', 'Arena', 'Ascona', 'Astra',
    'Calibra', 'Campo', 'Cascada', 'Cavalier', 'Combo', 'Combo Life', 'Combo Tour', 'Commodore',
    'Corsa', 'Crossland', 'Crossland X', 'Diplomat', 'Frontera', 'GT', 'Grandland', 'Grandland X',
    'Insignia', 'Insignia Ctry Tourer', 'Kadett', 'Kapitän', 'Karl', 'Manta', 'Meriva', 'Mokka',
    'Mokka X', 'Monterey', 'Monza', 'Movano', 'Nova', 'Olympia', 'Omega', 'Pick Up Sportscap',
    'Rekord', 'Rocks-e', 'Senator', 'Signum', 'Sintra', 'Speedster', 'Tigra', 'Vectra', 'Vivaro',
    'Zafira', 'Zafira Life', 'Zafira Tourer', 'Autre',
  ],
  PEUGEOT: [
    '1007', '104', '106', '107', '108', '2008', '201', '202', '203', '204', '205', '206', '207',
    '208', '3008', '301', '302', '304', '305', '306', '307', '308', '309', '4007', '4008', '401',
    '402', '403', '404', '405', '406', '407', '408', '5008', '504', '505', '508', '604', '605',
    '607', '806', '807', 'Bipper', 'Bipper Tepee', 'Boxer', 'Expert', 'Expert Tepee', 'J5',
    'Partner', 'Partner Tepee', 'RCZ', 'Rifter', 'Traveller', 'iOn', 'Autre',
  ],
  RENAULT: [
    '10', '11', '12', '14', '15/17', '16', '18', '19', '20', '21', '25', '30', '4/4L', '4CV',
    '5', '6', '8', '9', 'Alaskan', 'Arkana', 'Austral', 'Avantime', 'Captur', 'Celtaquatre',
    'Clio', 'Dauphine', 'Espace', 'Express', 'Floride Caravelle', 'Fluence', 'Frégate', 'Fuego',
    'Grand Espace', 'Grand Modus', 'Grand Scenic', 'Juvaquatre', 'Kadjar', 'Kangoo', 'Koleos',
    'Laguna', 'Latitude', 'Mascott', 'Master', 'Megane', 'Modus', 'Rafale', 'Rodeo', 'Safrane',
    'Scenic', 'Spider', 'Symbioz', 'Talisman', 'Trafic', 'Twingo', 'Twizy', 'Vel Satis', 'Wind',
    'Zoe', 'Autre',
  ],
  TOYOTA: [
    '2000 GT', '4-Runner', 'Alphard', 'Auris', 'Auris Touring Sports', 'Avalon', 'Avensis',
    'Avensis Verso', 'Aygo', 'Aygo X', 'C-HR', 'C-HR+', 'Camry', 'Carina', 'Celica', 'Corolla',
    'Corolla Verso', 'Corona', 'Cressida', 'Crown', 'Curren', 'Dyna', 'FCV', 'FJ', 'Fortuner',
    'GR Supra', 'GR86', 'GT86', 'HiAce', 'Highlander', 'Hilux', 'Land Cruiser', 'Lexus',
    'LiteAce', 'MR', 'Matrix', 'Mirai', 'PROACE CITY Verso', 'PROACE Combi', 'PROACE Verso',
    'Paseo', 'Picnic', 'Previa', 'Prius', 'Prius+', 'RAV4', 'Regius', 'Sienna', 'Sienta',
    'Starlet', 'Stout', 'Succeed', 'Supra', 'Tacoma', 'Tercel', 'TownAce', 'Tundra', 'Vellfire',
    'Venza', 'iQ', 'Autre',
  ],
  VOLKSWAGEN: [
    '181', 'Amarok', 'Arteon', 'Beetle', 'Bora', 'Buggy', 'CALIDORNIA', 'Caddy', 'California',
    'Caravelle', 'Coccinelle', 'Combi', 'Corrado', 'Crafter', 'Eos', 'Fox', 'Golf', 'ID. Buzz',
    'ID. Cross', 'ID.3', 'ID.4', 'ID.5', 'ID.6', 'ID.7', 'Iltis', 'Jetta', 'Karmann Ghia',
    'Käfer', 'LT', 'Lupo', 'Minibus', 'Multivan', 'New Beetle', 'Passat', 'Phaeton', 'Polo',
    'Routan', 'Santana', 'Scirocco', 'Sharan', 'T-Cross', 'T-Roc', 'T1', 'T2', 'T3', 'T4', 'T5',
    'T6', 'T7 Multivan', 'TAYRON', 'Taigo', 'Taro', 'Tiguan', 'Tiguan Allspace', 'Touareg',
    'Touran', 'Transporter', 'Up', 'VW-Busse', 'Variant', 'Vento', 'XL1', 'Autre',
  ],
  'ALFA ROMEO': [
    '145', '146', '147', '155', '156', '156 Crosswagon', '159', '164', '166', '33', '4C', '6C',
    '75', '8C', '90', 'Alfasud', 'Alfetta', 'Brera', 'GT', 'GTV', 'Giulia', 'Giulietta', 'Junior',
    'Junior Zagato', 'MiTo', 'Montreal', 'SZ/RZ', 'Spider', 'Sprint', 'Stelvio', 'Tonale', 'Autre',
  ],
  BENTLEY: [
    'Arnage', 'Azure', 'Bentayga', 'Brooklands', 'Continental', 'Continental GT',
    'Continental GTC', 'Continental R', 'Eight', 'Flying Spur', 'Mark VI', 'Mulsanne', 'S', 'T',
    'Turbo', 'Turbo R', 'Type R', 'Autre',
  ],
  CHEVROLET: [
    '150', '210', '2500', 'Alero', 'Astro', 'Avalanche', 'Aveo', 'Bel Air', 'Beretta', 'Biscayne',
    'Blazer', 'C1500', 'Camaro', 'Caprice', 'Captiva', 'Cavalier', 'Chevelle', 'Chevelle Malibu',
    'Chevy II', 'Chevy Van', 'Citation', 'Colorado', 'Concours', 'Corsica', 'Corvair', 'Corvette',
    'Cruze', 'Delray', 'Deluxe', 'El Camino', 'Epica', 'Evanda', 'Express', 'G', 'HHR', 'Impala',
    'K1500', 'K30', 'Kalos', 'Lacetti', 'Laguna', 'Lumina', 'Malibu', 'Matiz', 'Monte Carlo',
    'Monza', 'Mova', 'Niva', 'Nomad', 'Nova', 'Nubira', 'Orlando', 'Rezzo', 'S-10', 'SSR',
    'Silverado', 'Spark', 'Spécial', 'Suburban', 'Tahoe', 'Trailblazer', 'Trans Sport', 'Vega',
    'Venture', 'Volt', 'Autre',
  ],
  HONDA: [
    'Accord', 'Acty', 'Aerodeck', 'CR-V', 'CR-Z', 'CRX', 'City', 'Civic', 'Clarity', 'Concerto',
    'Element', 'FR-V', 'HR-V', 'Honda e', 'Insight', 'Integra', 'Jazz', 'Legend', 'Logo', 'MDX',
    'N 360', 'N 600', 'NSX', 'Odyssey', 'Pilot', 'Prelude', 'Quint', 'Ridgeline', 'S 500',
    'S 600', 'S 800', 'S2000', 'Shuttle', 'Stream', 'Z 600', 'ZR-V', 'e:Ny1', 'Autre',
  ],
  HUMMER: ['H1', 'H2', 'H3', 'Autre'],
  HYUNDAI: [
    'Accent', 'Atos', 'Azera', 'Bayon', 'Coupe', 'Elantra', 'Excel', 'Galloper', 'Genesis',
    'Getz', 'Grand Santa Fe', 'Grandeur', 'H-1', 'H-1 Starex', 'H-100', 'H-200', 'H350', 'Inster',
    'Ioniq', 'Ioniq 3', 'Ioniq 5', 'Ioniq 6', 'Ioniq 9', 'Kona', 'Lantra', 'Matrix', 'Nexo',
    'Pony', 'Santa Fe', 'Santamo', 'Satellite', 'Scoupe', 'Sonata', 'Staria', 'Terracan',
    'Trajet', 'Tucson', 'Veloster', 'Veracruz', 'XG', 'i10', 'i20', 'i30', 'i40', 'ix20', 'ix35',
    'ix55', 'Autre',
  ],
  JAGUAR: [
    '420', 'Daimler', 'E-Pace', 'F-Pace', 'F-Type', 'I-Pace', 'MK X', 'MKI', 'MKII', 'Mark IV',
    'Mark V', 'Mark VII VIII IX', 'S-Type', 'Sovereign', 'Type E', 'Type-S (1963-68)', 'X-Type',
    'XE', 'XF', 'XJ', 'XJ Série 1', 'XJ Série 2', 'XJ Série 3', 'XJ-SC', 'XJ12', 'XJ220', 'XJ40',
    'XJ6', 'XJ8', 'XJR', 'XJR-S', 'XJS', 'XJS cabriolet', 'XK', 'XK8', 'XKR', 'Autre',
  ],
  LAMBORGHINI: [
    '350 GT', '400 GT', 'Aventador', 'Countach', 'Diablo', 'Espada', 'Gallardo', 'Huracan',
    'Islero', 'Jalpa', 'Jarama', 'Miura', 'Murcielago', 'Revuelto', 'Silhouette', 'Urraco',
    'Urus', 'Autre',
  ],
  LANCIA: ['Aurelia', 'Beta', 'Dedra', 'Delta', 'Elefantino', 'Flaminia', 'Flavia', 'Fulvia', 'Gamma', 'Kappa'],
  'LAND-ROVER': [
    'Defender', 'Discovery', 'Discovery Sport', 'Freelander', 'Range Rover',
    'Range Rover Evoque', 'Range Rover Sport', 'Range Rover Velar', 'Serie 1', 'Serie 2',
    'Serie 3', 'Autre',
  ],
  LEXUS: ['CT', 'ES', 'GS', 'GX', 'IS', 'LBX', 'LC', 'LFA', 'LM', 'LS', 'LX', 'NX', 'RC', 'RX', 'RZ', 'SC', 'UX', 'Autre'],
  MASERATI: [
    '222', '228', '3200 GT', '3500 GT', '422', '430', '5000 GT', 'Biturbo', 'Bora', 'Coupe',
    'Ghibli', 'GranCabrio', 'GranTurismo', 'Gransport', 'Grecale', 'Indy', 'Khamsin', 'Kyalami',
    'Levante', 'MC PURA', 'MC20', 'Merak', 'Mexico', 'Mistral', 'Quattroporte', 'Sebring',
    'Shamal', 'Spyder', 'Autre',
  ],
  MAZDA: [
    '121', '323', '626', '929', 'B Series', 'BT-50', 'CX-3', 'CX-30', 'CX-5', 'CX-60', 'CX-6e',
    'CX-7', 'CX-9', 'Demio', 'E Series', 'MPV', 'MX-3', 'MX-30', 'MX-5', 'MX-6', 'Mazda 2',
    'Mazda 3', 'Mazda 5', 'Mazda 6', 'Premacy', 'RX-7', 'RX-8', 'Tribute', 'Xedos', 'Autre',
  ],
  MCLAREN: [
    '540C', '570GT', '570S', '600LT', '620R', '650S Coupé', '650S Spider', '675LT',
    '675LT Spider', '720S', '750S', '765LT', 'F1', 'GT', 'MP4 12C', 'MP4 12C Spider', 'P1',
    'Senna GTR', 'Autre',
  ],
  'MG/MG MOTOR': [
    '1100', '1300', 'A', 'B', 'C', 'Cyberster', 'EHS', 'HS', 'IM5', 'IM6', 'MARVEL R', 'MG3',
    'MG4', 'MG4 Urban', 'MG5', 'MGF/MGTF', 'MGS5', 'MGS6', 'MGS9', 'Midget', 'T-Type Midget',
    'TB/TC/TD/TF', 'ZR', 'ZS', 'ZT', 'Autre',
  ],
  MITSUBISHI: [
    '3000 GT', 'ASX', 'Canter', 'Carisma', 'Colt', 'Cordia', 'Cosmos', 'Diamante', 'Eclipse',
    'Eclipse Cross', 'Galant', 'Galloper', 'Grandis', 'L200', 'L300', 'L400', 'Lancer',
    'Montero', 'Outlander', 'Pajero', 'Pajero Pinin', 'Pajero Sport', 'Pick-up', 'Santamo',
    'Sapporo', 'Sigma', 'Space', 'Space Star', 'Starion', 'Tredia', 'i-Miev', 'Autre',
  ],
  PONTIAC: [
    'Bonneville', 'Catalina', 'Chieftain', 'Excecutive', 'Fiero', 'Firebird', 'G6', 'GT37',
    'GTO', 'Grand Am', 'Grand Prix', 'Grand Ville', 'Le Mans', 'Solstice', 'Star Chief',
    'Super Chief', 'Tempest', 'Trans Am', 'Trans Sport', 'Ventura', 'Autre',
  ],
  PORSCHE: [
    '356', '718', '911', '912', '914', '918', '924', '928', '944', '959', '968', 'Boxster',
    'Carrera GT', 'Cayenne', 'Cayman', 'Macan', 'Panamera', 'Taycan', 'Autre',
  ],
  'ROLLS-ROYCE': [
    'Continental', 'Corniche', 'Cullinan', 'Dawn', 'Flying Spur', 'Ghost', 'Phantom', 'Shadow',
    'Silver', 'Silver Cloud', 'Silver Dawn', 'Silver Ghost', 'Silver Seraph', 'Silver Shadow',
    'Silver Spirit', 'Silver Spur', 'Silver Wraith', 'Spirit', 'Springfield', 'Wraith', 'Autre',
  ],
  SEAT: [
    'Alhambra', 'Altea', 'Altea XL', 'Arona', 'Arosa', 'Ateca', 'Cordoba', 'Exeo', 'Ibiza',
    'Inca', 'Leon', 'Malaga', 'Marbella', 'Mii', 'Tarraco', 'Terra', 'Toledo', 'Autre',
  ],
  SKODA: [
    '105', '120', '130', '135', 'Citigo', 'Elroq', 'Enyaq', 'Epiq', 'Fabia', 'Favorit', 'Felicia',
    'Felicia Pick up', 'Forman', 'Kamiq', 'Karoq', 'Kodiaq', 'Octavia', 'Peaq', 'Praktik',
    'Rapid', 'Roomster', 'Scala', 'Superb', 'Yeti', 'Autre',
  ],
  SMART: ['#1', '#3', '#5', 'Crossblade', 'Forfour', 'Fortwo', 'Roadster', 'Autre'],
  SUZUKI: [
    'APV', 'Across', 'Alto', 'Baleno', 'Cappucino', 'Carry', 'Celerio', 'Grand Vitara', 'Ignis',
    'Jimny', 'Kizashi', 'Liana', 'Lj', 'S-Cross', 'SX4', 'SX4 S-Cross', 'Samurai', 'Splash',
    'Super-Carry', 'Swace', 'Swift', 'Vitara', 'Wagon R+', 'X-90', 'iK-2', 'Autre',
  ],
  VOLVO: [
    '240', '244', '245', '262', '264', '265', '340', '343', '345', '360', '440', '460', '480',
    '740', '744', '745', '760', '780', '850', '855', '940', '944', '945', '960', '965', 'Amazon',
    'C30', 'C40', 'C70', 'ES90', 'EX30', 'EX30 Cross Country', 'EX60', 'EX90', 'P 1800',
    'P 1900', 'PV', 'S40', 'S60', 'S60 Cross Country', 'S70', 'S80', 'S90', 'Série 120',
    'Série 140', 'Série 160', 'V40', 'V40 Cross Country', 'V50', 'V60', 'V60 Cross Country',
    'V70', 'V70 Cross Country', 'V90', 'V90 Cross Country', 'XC40', 'XC60', 'XC70', 'XC90',
    'Autre',
  ],
};

// Trim (finition) name lists for specific model x make combos. A make not present here, or a
// model not present under a make that IS here, has no per-model list -- see the seed script for
// how those are filled in.
export const FINITIONS_BY_MODEL: Record<string, Record<string, string[]>> = {
  'MERCEDES-BENZ': {
    'Classe C': [
      '43 AMG', '450 AMG', '63 AMG', 'AMG', 'AMG +', 'AMG Edition 1', 'AMG Edition 1 grise',
      'AMG F1 Edition', 'AMG Limited Edition', 'AMG Line', 'AMG Line +', 'AMG Night Edition',
      'AMG S', 'AMG S Edit. 1 grise', 'AMG S Edit. 1 jaune', 'AMG S Edition 1', 'AMG Sport',
      'Avantgarde', 'Avantgarde Edition', 'Avantgarde Evolution', 'Avantgarde Executive',
      'Avantgarde Launch Ed', 'Avantgarde Line', 'Avantgarde Line +', 'Avantgarde Luxe',
      'Avantgarde Optimum', 'Avantgarde Pk Luxe', 'Avant. Lau Ed Pk Lx', 'Base', 'Business',
      'Business Executive', 'Business Line', 'Business Line +', 'Business Line Exe', 'Classic',
      'Classic Clim', 'Classic Edition', 'Classic Launch Edit.', 'Classic Laun Ed Pk L',
      'Classic Optimum', 'Classic Temperee', 'Contact', 'Edition +', 'Edition 1',
      'Edition 1 AMG', 'Edition 507', 'Elegance', 'Élégance', 'Elegance Clim',
      'Elegance Edition', 'Elegance Evolution', 'Élégance Executive', 'Élégance Lau Ed Pk L',
      'Élégance Launch Edit', 'Elegance Luxe', 'Elegance Optimum', 'Elegance Pack Luxe',
      'Esprit', 'Executive', 'Fascination', 'Night Edition', 'Sport', 'Sport Clim',
      'Sport Edition', 'Sportline', 'Sport Optimum', 'Version Sport',
    ],
    'AMG GT': [
      '43 AMG', '53 AMG', '55 AMG', '63 AMG', '63 AMG Edition 1', 'Base', 'E Performance', 'GT',
      'GT Black Series', 'GT C', 'GT C Edition 50', 'GT R', 'GT R Pro', 'GT S',
      'Motorsport Collec Ed', 'Pro',
    ],
    'Classe A': [
      '35 AMG', '35 AMG Edition 1', '45 AMG S', '45 AMG S Edition 1', 'AMG', 'AMG Edition 1',
      'AMG Edition 55', 'AMG Exclusive Design', 'AMG Line', 'AMG Line Edition 1', 'AMG S',
      'AMG S Limited Edit', 'Avantgarde', 'Avantgarde Contact', 'Avantgarde ContactII',
      'Avantgarde Fascinat', 'Avantgarde Optimum', 'Avantg. Fascination', 'Base',
      'Bus Executive Ed', 'Business', 'Business Edition', 'Business Executive', 'Business Line',
      'Classic', 'Classic Contact', 'Classic Contact II', 'Classic Fascination',
      'Classic Optimum', 'Designo', 'Edition', 'Edition 140', 'Edition Street Style',
      'Elegance', 'Élégance', 'Elegance Contact', 'Élégance Contact', 'Elegance Contact II',
      'Elegance Fascination', 'Elegance Optimum', 'Élégance Optimum', 'Evolution Avantgarde',
      'Fascination', 'Final Edition', 'Grand Edition', 'Inspiration', 'Intuition',
      'Motorsport Edition', 'Polar Star', 'Progressive Line', 'Sensation', 'Special Edition',
      'Sport', 'Sport Edition', 'Sport Motorsport Ed.', 'Sport Optimum', 'Star Edition',
      'Style Line', 'Version Sport', 'WhiteArt Edition', 'Yellow Night Edition',
    ],
    'Classe E': [
      '53 AMG', 'AMG', 'AMG Avantgarde', 'AMG Edition 1', 'AMG Line', 'AMG Line+', 'AMG S',
      'AMG S Final Edition', 'Avantgarde', 'Avantgarde Clim', 'Avantgarde Edition',
      'Avantgarde Edition +', 'Avantgarde Exécutive', 'Avantgarde Line', 'Avantgarde Line+',
      'Avantgarde Optimum', 'Avantgarde Sport Ed.', 'Base', 'Base+', 'Business',
      'Business Executive', 'Classic', 'Classic Clim', 'Classic Edition', 'Classic Edition +',
      'Classic Optimum', 'Design', 'Elegance', 'Elegance Clim', 'Elegance Edition',
      'Elegance Edition +', 'Élégance Exécutive', 'Elegance Optimum', 'Élégance Optimum',
      'Exclusive Line', 'Exclusive Line+', 'Executive', 'Fascination', 'Pack Luxe Avantgarde',
      'Pack Luxe Elegance', 'Pk Luxe Avant. Ed. +', 'Pk Luxe Eleg. Ed. +', 'Prestige',
      'Prime edition', 'Reference', 'Reference Clim', 'Sport Edition', 'Sportline',
    ],
    'Classe GLC': [
      'AMG', 'AMG +', 'AMG Line', 'AMG Line +', 'AMG Line Launch Ed', 'AMG S', 'AMG S +',
      'AMG S Edition 1', 'AMG S Ltd Edition', 'Avantgarde Li Launch', 'Avantgarde Line',
      'Avantgarde Line +', 'Base', 'Business', 'Business Executive', 'Business Line',
      'Business Line +', 'Business Line Exe', 'Business Line Launch', 'Executive', 'Fascination',
      'Launch Edition', 'Sportline',
    ],
    'Classe SLK': ['AMG', 'AMG Contact', 'Base', 'Contact', 'Edition 1', 'Edition 10', 'Final Edition', 'Special Edition'],
    Sprinter: ['Base', 'Confort', 'Luxe', 'Pro', 'Select', 'Standard'],
  },
  AUDI: {
    A3: [
      'Advanced', 'Advanced Edition', 'Advanced Ed. Plus', 'Ambiente', 'Ambition',
      'Ambition Luxe', 'Ambition P. Stream', 'Attraction', 'Attraction P. Stream', 'Avus',
      'Base', 'Business Executive', 'Business line', 'Competition', 'Design', 'Design Edition',
      'Design luxe', 'Design Luxe', 'Exclusive Line', 'Midnight Series', 'Pack Attraction',
      'Pack Sport', 'S line', 'S line Plus', 'Sport', 'Sport Design', 'Sport Limited',
      'Streamline',
    ],
    Q3: [
      'Advanced', 'Ambiente', 'Ambition Luxe', 'Attraction', 'Avus', 'Base', 'Black Edition',
      'Business Executive', 'Business line', 'Design', 'Design Luxe', 'Limited',
      'Midnight Series', 'S Edition', 'S line', 'S line plus', 'Sport Design', 'Urban Cross',
      'Urban Sport', 'Urban Techno',
    ],
    Quattro: ['Base'],
    TT: [
      '20 Years', 'Ambition Luxe', 'Base', 'Compétition Plus', 'Design Edition',
      'Design Edition II', 'Héritage', 'Le Mans', 'S line', 'Streamline',
    ],
    S3: ['Base'],
  },
  CITROEN: {
    C3: [
      'Airdream', 'Airplay', 'Attraction', 'Base', 'Blue Note', 'Business', 'BUSINESS', 'Classic',
      'Collection', 'COLLECTION', 'Collection II', 'Collection III', 'Confort',
      'Confort Business', 'C-Series', 'ELLE', 'Exclusive', 'Feel', 'Feel 3', 'Feel Business',
      'Feel Edition', 'Feel Pack', 'Furio', 'Génération', 'Graphic', 'JCC+', 'Live', 'MAX',
      'Music Box', 'Music Touch', 'Open Way', 'Origins', 'Pack', 'Pack Ambiance', 'Pack Clim',
      'Pack Leader', 'Pack Tic Tac', 'Passion Bleus', 'PLUS', 'PS VITA', 'Pulp', 'Red Block',
      'Rossignol', 'Saint James', 'Sélection', 'Shine', 'Shine Business', 'Shine Pack',
      'So Chic', 'Stop & Start', 'SX', 'SX Pack Ambiance', 'SX Pack Clim', 'Tic Tac 05', 'Tonic',
      'VirginMega', 'Vitamine', 'Vitamine II', 'VTR', 'X', 'X-TR', 'XTR 2', 'YOU', 'YOU!',
      'YOU PACK BUSINESS', 'YOU + Pack Plus',
    ],
    'C4 Cactus': [
      'Business', 'C-Series', 'Feel', 'Feel Business', 'Feel Edition', 'Live', 'OneTone',
      'Origins', 'Rip Curl', 'Shine', 'Shine Business', 'Shine Edition', 'Start',
    ],
    'C4 Picasso': [
      'Airplay', 'Attraction', 'Base', 'Business', 'Business +', 'Business Pack Amb',
      'Collection', 'Confort', 'Exclusive', 'Exclusive Black Top', 'Feel', 'Feel Edition',
      'Intensive', 'Live', 'Millenium', 'Millenium II', 'Music Box', 'Music Touch', 'Pack',
      'Pack Ambiance', 'Pack Dynamique', 'Passion Bleus', 'Rip Curl', 'Rossignol',
      'Rossignol II', 'Sélection', 'Shine',
    ],
  },
  FIAT: {
    '500': [
      '120th', '500 America', '500byGucci', '500 Liberty & Art F.', 'Action', 'Action Plus',
      'Anniversario', 'Base', 'Bianco Amore Ed', 'Bi-Color', 'By Diesel', 'by Harcourt', 'Club',
      'Collezione', 'Collezione Fall', 'Color Therapy', 'Cult', 'Diva', 'Dolcevita',
      'Dolcevita Plus', 'France Edition', 'Giorgio Armani C. Ed', 'GQ', 'Hey Google', 'Icône',
      'Icône Plus', 'La Prima', 'La Prima by Bocelli', 'Launch Edition', 'Live Edizione',
      'Lounge', 'Mirror', 'Pack Cft&Style&Tech', 'Pack Confort', 'Pack Confort & Style',
      'Pack Confort & Tech', 'Pack Style', 'Pack Style & Tech', 'Pack Tech', 'Passion',
      'Petite Robe Noire', 'Pop', 'Popstar', 'Pop Style', '(RED)', '(RED) 2.0', 'Repetto',
      'Riva', 'Rockstar', 'Ron Arad Edition', 'Rosso Amore Edizione', 'S', 'S Limited',
      'So Pink', 'S Plus', 'Sport', 'Sport & Style', 'Star', 'Street', 'Torino', 'TwinAir',
      'TwinAir+', 'Urban', 'Vintage57', 'Web Collezione',
    ],
  },
  FORD: {
    'C-MAX': [
      'Ambiente', 'Business', 'Business Nav', 'Connection', 'Edition', 'Edition Limitée',
      'Ghia', 'Nordic Blue', 'S', 'Sport', 'Titanium', 'Titanium X', 'Trend', 'Trend Business',
      'Très spéciale',
    ],
    Explorer: ['Base', 'Pack Collection', 'Pack Premium', 'Platinum', 'Select', 'ST-Line', 'Style'],
    Mustang: ['Base', 'Bullitt', 'Dark Horse', 'GT', 'Mach 1', 'Mustang55', 'V8 GT'],
    Mondeo: [
      'Ambiente', 'Ambiente Pack', 'Base', 'Business', 'Business Nav', 'Celebration',
      'Centenium', 'CLX', 'ECOnetic', 'Edition', 'Edition Limitée', 'Elance', 'Excellence',
      'Executive', 'Ghia', 'Ghia X', 'GL', 'GLX', 'LX', 'Mondial', 'Nordic', 'Ovation',
      'Ovation II', 'S', 'Saphir', 'Saphir ABS', 'Saphir Pack', 'Si', 'Sport Edition',
      'Sport Platinium', 'ST', 'ST 200', 'ST-Line', 'Titanium', 'Titanium Business',
      'Titanium X', 'Trend', 'Trend Business', 'Très spéciale', 'UEFA', 'Vignale', 'X-Trend',
      'X-Trend 5-T',
    ],
  },
  MINI: {
    Cooper: ['Blackyard', 'Classic', 'Edition Paul Smith', 'Essential', 'Favoured', 'JCW', 'JCW Victory Edition'],
    Countryman: [
      'Blackyard', 'Bricklane', 'Business', 'Business Call', 'Business Design',
      'Business Executive', 'Business Trip', 'Chili', 'Chili +', 'Classic', 'Cooper',
      'Cooper S', 'Dakar Winner', 'Edition Premium', 'Edition Premium Plus',
      'Edition Untamed Plus', 'Essential', 'Exclusive Pro', 'Exquisite', 'Favoured', 'GetAway',
      'Highlands', 'JCW', 'JCW Exclusive Design', 'JCW Ultimate', 'John Cooper Works',
      'Longstone', 'Longstone White Silv', 'Northwood', 'Oakwood', 'One', 'Pack Chili',
      'Pack JCW Extérieur', 'Pack JCW Intérieur', 'Pack Red Hot Chili', 'Pack Red Hot Chil II',
      'Pack Salt', 'Park Lane', 'Red Hot Chili', 'Salt', 'Untamed', 'Yours',
    ],
    Mini: [
      '1to6 Edition', '211 JCW Edition', '50 Camden', '50 Mayfair', 'Always Open',
      'Baker Street', 'Bayswater', 'Blackfriars', 'Brick Lane', 'Business', 'Business Call',
      'Business Design', 'Business Trip', 'Checkmate', 'Chili', 'Chili II', 'Classic', 'Cooper',
      'Cooper S', 'Cooper SE', 'Cooper S GT', 'Docklands', 'Edition 60 Years',
      'Edition Anniversary', 'Edition Camden', 'Edition Greenwich', 'Edition Premium',
      'Edition Premium Plus', 'Edition Seaside', 'Editio Resolute Plus', 'Ed Resolut Essential',
      'Electric', 'Electric Collec 2021', 'Essential', 'Exclusive Design', 'Exquisite',
      'Exquisite II', 'Fashion', 'GPII', 'Green Park', 'Heddon Street', 'Highgate', 'Hyde Park',
      'JCW', 'JCW GP', 'JCW GP Inspired', 'JCW GP Ultimate', 'JCW Plus', 'JCW Pro',
      'JCW Ultimate', 'Marylebone', 'Mat Edition', 'Mint', 'Monte Carlo', 'mosaert', 'One',
      'One Pack', 'Pack Brick Lane II J', 'Pack Brick Lane II V', 'Pack Chili', 'Pack Chili +',
      'Pack Curry', 'Pack Hot Spice', 'Pack Hot Spice +', 'Pack JCW', 'Pack JCW Extérieur',
      'Pack JCW Intérieur', 'Pack Red Hot Chili', 'Pack Red Hot Chil II', 'Pack Salt',
      'Pack Salt +', 'Park Lane', 'Pure Burgundy', 'Red Hot Chili', 'Resolute', 'Salt', 'Seven',
      'Shoreditch', 'Sidewalk', 'WC50', 'Yours',
    ],
  },
  NISSAN: {
    'X-Trail': [
      'Acenta', 'Black Edition', 'Business Edition', 'Columbia Confort', 'Columbia Elégance',
      'Columbia Plaza', 'Columbia Sport', 'Confort', 'Confort Pack Family', 'Connect Edition',
      'Distinction', 'Elégance', 'Excess', 'Free-Ride', 'Giant', 'LE', 'Luxe', 'N-Connecta',
      'N-Tec', 'N-Trek', 'Platinum', 'Plaza', 'SE', 'Sport', 'Style Edition', 'Tekna', 'Tekna+',
      'Ultimate', 'Visia', 'White Edition', 'XE',
    ],
    Qashqai: [
      '360', 'Acenta', 'Acenta Navi', 'Acenta Pack', 'Black Edition', 'Business+',
      'Business Edition', 'Connect Edition', 'Design Edition', 'Drive Edition', 'Icon',
      'N-Connecta', 'N-Design', 'N-Design+', 'N-Motion', 'N-Style', 'N-TEC', 'N-Vision',
      'Premier Edition', 'Premiere Edition', 'Shadow', 'Sound&Style', 'TechView Edition',
      'Tekna', 'Tekna+', 'Tekna Sport', 'Ultimate Edition', 'Visia', 'White Edition',
    ],
  },
  OPEL: {
    Astra: [
      '111', '90e Anniversaire', 'Base', 'Bertone', 'Bertone Pack', 'BiTurbo', 'Black Edition',
      'Black & White', 'Business', 'Business Connect', 'Business Edition', 'CD', 'CDi', 'CDTI',
      'CDX', 'Century', 'Comfort', 'Connect Pack', 'Cool Line', 'Cool Line²', 'Cosmo',
      'Cosmo Pack', 'Cosmo Panoramique', 'Design & Tech', 'Dynamic', 'Edition',
      'Edition 120 ans', 'Edition 2000', 'Edition Business', 'Edition GPS', 'Edition Plus',
      'Elegance', 'Elegance Business', 'Elite', 'Enjoy', 'Essentia', 'Euro 96', 'Fashion', 'GL',
      'GL Pack', 'GLS', 'GLT', 'Grand Luxe', 'GS', 'GSe', 'GSi', 'GS Line', 'Innovation',
      'Key West', 'Limited Edition', 'Linea Rossa', 'Magnetic', 'Metal Line', 'OPC',
      'Opel 2020', 'Panoramique', 'Power Pack', 'S', 'Si', 'Silver Edition', 'Si Power Pack',
      'Sport', 'Sport Pack', 'Tiffany', 'Turbo Pack', 'Ultimate', 'White Edition',
    ],
    // Cut short in the source data.
    Corsa: [
      '111', '150ème Anniversaire', '40ème Anniversaire', 'Active', 'Base', 'Black Edition',
      'Business', 'Business Connect', 'Business Edition', 'CDX',
    ],
  },
  PEUGEOT: {
    '5008': [
      'Access', 'Access Business', 'Active', 'Active Bus. 7 places', 'Active Business',
      'Active Pack', 'Allure', 'Allure 7 places', 'Allure Business', 'Allure Pack', 'Business',
      'Business Pack', 'Confort Pack', 'Crossway', 'Family', 'Family II', 'GT', 'GT Exclusive',
      'GT Line', 'GT Pack', 'Premium', 'Premium Pack', 'Premium Pk Edit', 'Roadtrip', 'Style',
      'Style II', 'Style III', 'Style IV',
    ],
    '206': [
      '2000', 'Access', 'Active', 'Attractive', 'Base', 'Executive', 'Génération', 'Griffe',
      'GT', 'NavTech', 'Navteq', 'Pack Limited', 'Pop Art', 'Pop Art Clim', 'Quiksilver', 'RC',
      'Roland Garros', 'Roxy', 'S16', 'Sport', 'Sportium', 'Sport Pack', 'Style', 'Trendy',
      'Urban', 'Urban Move', 'Urban Move II', 'X-BOX 360', 'X Line', 'X Line Clim', 'XR',
      'XR Presence', 'XS', 'XS Pack AC Reg', 'XS Premium', 'XS Sport', 'XT', 'XT Pack AC Reg',
      'XT Pack Clim', 'XT Premium',
    ],
    '208': [
      'Access', 'Active', 'Active Business', 'Active Pack', 'Allure', 'Allure Business',
      'Allure Pack', 'Business', 'Business Pack', 'Business  Pack', 'Edition', 'Envy',
      'E-Style', 'Féline', 'GT', 'GT Exclusive', 'GTi', 'GTi 30th', 'GTi by Peugeot Sport',
      'GTi Limited Edition', 'GT Line', 'GT Pack', 'Ice Velvet', 'Intuitive', 'Ligne S', 'Like',
      'Roadtrip', 'Roland Garros', 'Signature', 'Street', 'Style', 'Tech Edition',
      'Urban Soul', 'XY', 'XY JBL',
    ],
    '3008': [
      'Access', 'Access Business', 'Active', 'Active Business', 'Active Pack', 'Allure',
      'Allure Business', 'Allure Pack', 'Base', 'Business', 'Business Pack', 'Confort Pack',
      'Crossway', 'DM First Edition', 'Féline', 'GT', 'GT Exclusive', 'GT Line', 'GT Pack',
      'HYbrid4 Pack', 'Limited Edition', 'Napapijri', 'Premium', 'Premium Pack', 'Roadtrip',
      'Roland Garros', 'Roland Garros II', 'Style', 'Style II', 'Style III',
    ],
    '2008': [
      'Access', 'Active', 'Active Business', 'Active Pack', 'Allure', 'Allure Business',
      'Allure Pack', 'Business', 'Business Pack', 'Crossway', 'Crossway II', 'Edition', 'Envy',
      'Féline Cuivre', 'Féline Titane', 'GT', 'GT Exclusive', 'GT Line', 'GT Pack',
      'Red Urban Cross', 'Roadtrip', 'Signature', 'Style', 'Urban Cross', 'Urban Cross II',
    ],
    '1007': [
      'Black & Silver', 'Cappucino', 'Dolce', 'Dolce Avant Premiere', 'Dolce Avt Prem. TO',
      'Dolce Pack', 'Pack Limited', 'RC Line', 'Roxy', 'Sporty', 'Sporty Avant Premier',
      'Sporty Avt Prem. TO', 'Sporty Pack', 'Trendy', 'Vitamine',
    ],
  },
  RENAULT: {
    'Grand Scenic': [
      '15th', 'Alyum', 'Authentique', 'Base', 'Black Edition', 'Bose', 'Bose Edition',
      'Business', 'Business Intens', 'Carminat', 'Carminat TomTom', 'Confort Authentique',
      'Confort Dynamique', 'Confort Expression', 'Dynamique', 'Emotion', 'Energy', 'Evolution',
      'Exception', 'Executive', 'Expression', 'Initiale', 'Initiale Paris', 'Intens', 'Jade',
      'Latitude', 'Life', 'Limited', 'Luxe Dynamique', 'Luxe Privilège', 'Nouvelle Limited',
      'Pack Authentique', 'Pack Expression', 'Prima', 'Privilège', 'Sport Dynamique',
      'Sport Privilège', 'Techno', 'TomTom Live', 'Trend', 'Zen',
    ],
    '4/4L': ['Evolution', 'Iconic', 'Iconic Plein Sud', 'Techno', 'Techno Plein Sud'],
    '4CV': ['Base'],
    Scenic: [
      '15th', 'Aida', 'Aigle', 'Aigle DVD', 'Air', 'Alizé', 'Alyum', 'Authentique', 'Base',
      'Black Edition', 'Bose', 'Bose Edition', 'Business', 'Business Intens', 'Carminat',
      'Confort Authentique', 'Confort Dynamique', 'Confort Expression', 'Conquest', 'Dynamique',
      'Edition One', 'Egeus', 'Emotion', 'Energy', 'Evolution', 'Exception', 'Executive',
      'Expression', 'Expression Pack', 'Fairway', 'Fidji', 'Initiale', 'Initiale Paris',
      'Intens', 'Jade', 'Kaleido', 'Latitude', 'Life', 'Limited', 'Luxe Dynamique',
      'Luxe Privilège', 'Nouvelle Limited', 'Pack Authentique', 'Pack Cuir', 'Pack Expression',
      'Pépite', 'Prima', 'Privilège', 'Privilège Pack Cuir', 'RTA', 'RTE', 'RXE', 'RXE Clim',
      'RXi', 'RXT', 'Salomon', 'Sport Dynamique', 'Sport Privilège', 'Sport Way', 'Team Rugby',
      'Techno', 'Techno opt es Alpine', 'Techno opt Iconic', 'TomTom Live', 'Trend', 'Zen',
    ],
    Twingo: [
      'Access', 'Air', 'Alizé', 'Art Collection', 'Authentic', 'Authentique', 'Base', 'Benetton',
      'Campus', 'Cinetic', 'Coach', 'Collector', 'Collector Clim', 'Confort Authentique',
      'Cosmic', 'Dolce Vita', 'Dynamique', 'Easy', 'Easy Clim', 'Edition One', 'Elite Models',
      'Emotion', 'Equilibre', 'Evolution', 'Expression', 'Fidji', 'Génération', 'Gordini',
      'Gordini RS', 'GT', 'Helios', 'Hipanema', 'Initiale', 'Intens', 'Intens 2', 'Jade',
      'Jungle', 'Kenzo', 'Kiss cool', 'Kiss Cool', 'La Parisienne', 'Le Coq Sportif', 'Life',
      'Life 2', 'Limited', 'Luxe Privilège', 'Matic', 'Mauboussin', 'Midnight', 'Miss Sixty',
      'Night&Day', 'Nokia', 'Oasis', 'Ovalie', 'Pack', 'Pack Authentique', 'Pack Clim',
      'Pack Plus', 'Pépite', 'Perrier', 'Privilège', 'Purple', 'RedBull Racing RB7',
      'Red Night', 'Renault Sport', 'Rip Curl', 'Rive Gauche', 'RS', 'Sari', 'Signature',
      'Summertime', 'Team Rugby', 'Techno', "Tech'Run", 'Trend', 'Urban Night', 'Vibes',
      'Walkman', 'Wind', 'XV de France', 'Yahoo', 'Zen',
    ],
    Trafic: [
      'Authentique', 'Base', 'Confort', 'Equilibre', 'Escapade', 'Evado', 'Evolution',
      'Exécutive', 'Expression', 'Iconic', 'Intens', 'Intens2', 'Life', 'Pack Clim',
      'Pack Plus', 'Privilège', 'Signature', 'SpaceClass', 'Techno', 'Zen',
    ],
  },
  TOYOTA: {
    'Auris Touring Sports': [
      'Active', 'Active Pro', 'Business', 'Collection', 'Design', 'Design Business', 'Dynamic',
      'Dynamic Business', 'Executive', 'Feel!', 'Freestyle', 'Lounge', 'Salomon', 'SkyBlue',
      'Style', 'TechnoLine', 'Tendance', 'Tendance Business',
    ],
    Auris: [
      'Active', 'Active Pro', 'Business', 'Clean Power', 'Clean Pw Sportline', 'Collection',
      'Connect', 'Design', 'Design Business', 'Dynamic', 'Dynamic Business',
      'Dynamic Pack GPS', 'Executive', 'Executive Connect', 'Feel!', 'Les Bleus',
      'Limited Edition', 'Lounge', 'Luna', 'Luna Pack', 'Millenium', 'Millenium Pack',
      'SkyBlue', 'Sol', 'Sportline', 'Sportline Connect', 'Style', 'TechnoLine', 'Tendance',
      'Tendance Business', 'Terra',
    ],
    Corolla: [
      '4x4', 'Active', 'Base', 'Collection', 'Design', 'Desir', 'Dynamic', 'Dynamic Business',
      'G5', 'G6', 'GL', 'GR Sport', 'GR Sport Mat Edition', 'GT', 'JBL Edition', 'Les Bleus',
      'Luna', 'Sol', 'Sport', 'Techno', 'Terra', 'Terra Base', 'Terra Pack', 'Trek', 'TS', 'XL',
      'XLI', 'XLS', 'XLS Desir',
    ],
    'Land Cruiser': [
      '50ème Anniversaire', 'Court LX', 'Court VX', 'Decouvrable', 'Eden Park', 'First Edition',
      'Gentleman Farmer', 'GX', 'LeCap', 'Légende', 'Légende Pack', 'Life', 'Lounge',
      'Lounge Pack Premium', 'Lounge Pack Techno', 'Moyen FRP', 'Moyen LX', 'Moyen VX',
      'Tole Court', 'VX', 'VX Clim', 'VXE', 'VX Pack', 'VX Pack Cuir', 'VXV',
    ],
  },
  VOLKSWAGEN: {
    Passat: [
      'Bagatelle', 'Base', 'Bel Air', 'Biker', 'BlueMotion', 'BlueMotion Business',
      'BlueMotion Conf.', 'BlueMotion Trendline', 'Business', 'Business Line',
      'Business Line 2', 'Business Line GPS', 'Carat', 'Carat Ed. Individual', 'Carat Edition',
      'Carat Exclusive', 'Carat GPS', 'CL', 'Confort', 'Confortline', 'Confortline Business',
      'Connect', 'Design Edition', 'Elegance', 'Embassy', 'Embassy 2', 'Exclusive', 'GL', 'GT',
      'GTE', 'GTE Business', 'GTE Life Plus', 'Life', 'Life Plus', 'Lounge', 'Pack', 'Pack Plus',
      'R36', 'R Line', 'R-Line', 'Sélection', 'Sélection 2', 'Sport', 'Sportline', 'Style',
      'Trend', 'Trendline', 'Trendline Business', 'Ultimate', 'W8',
    ],
    Polo: [
      'Active', 'Air Plus', 'Allstar', 'Base', 'Base Business', 'Beats Audio', 'BlueGT',
      'BlueMotion', 'BlueMotion Business', 'Business', 'Carat', 'Carat Exclusive',
      'Carat Heuer', 'Clim', 'Concept', 'Concept 2', 'Confort', 'Confortline',
      'Confortline Business', 'Confort Plus', 'Connect', 'Copper Line', 'Cup', 'Cup 2',
      'Cup 2007', 'Cursus', 'Design Plus', 'Dune', 'Edition', 'Edition 50', 'Elle', 'ESP Plus',
      'First Edition', 'Fox', 'GL', 'GT', 'GTI', 'GTI Edition 25', 'Hudson', 'IKKS', 'IQ.Drive',
      'Life', 'Life Business', 'Life Edition', 'Life Plus', 'Lounge', 'Lounge Business',
      'Match', 'Match 2', 'Match 2 Confort', 'Match 2 Sport', 'Match ABS', 'Match Confort',
      'Miami', 'Music Plus', 'Open Air', 'Pack', 'Pack ABS', 'Pack Clim', 'Polo', 'R Line',
      'R-Line', 'R-Line Edition', 'R-Line Exclusive', 'R WRC', 'Sport', 'Sport Limited',
      'Sportline', 'Style', 'Style Exclusive', 'TO', 'Town', 'Trend', 'Trendline',
      'Trendline Business', 'Trend Pack', 'United', 'VW Edition', 'Wembley', 'Wembley Clim',
      'Wembley Plus ESP',
    ],
    Golf: [
      'Active', 'Allstar', 'Alltrack', 'Anniversary', 'Ascott', 'Avant Garde', 'Base',
      'Bel Air', 'Bon Jovi', 'Boston', 'Business', 'Carat', 'Carat Edition', 'Carat Exclusive',
      'Carat GL', 'Carat GLI', 'Carat GT', 'Carat GTI', 'Carat GTI 16V', 'CL', 'Classic Line',
      'Clim', 'Clim Pack', 'CL Pack', 'Coast', 'Collector', 'Concept', 'Confort', 'Confortline',
      'Confortline Business', 'Confort Plus', 'Connect', 'Cup', 'Cup 2', 'Design Edition',
      'Ecomatic', 'Edition', 'Edition 40', 'Edition 50', 'Family', 'Family Confort',
      'First Edition', 'GL', 'GL Clim', 'GLI', 'GLI Clim', 'Golf', 'GT', 'GT Clim', 'GTD',
      'GTD Spécial', 'GTE', 'GTI', 'GTI 16S', 'GTI 16V Anniversaire', 'GTI 16V Edition',
      'GTI 16V Edition Clim', 'GTI Anniversaire', 'GTI Clubsport', 'GTI Clubsport 45',
      'GTI Edition', 'GTI Edition 30', 'GTI Edition 35', 'GTI Edition 50', 'GTI Edition Clim',
      'GTI Performance', 'GTI Pirelli 230', 'GTI TCR', 'GT Sport', 'IQ.Drive', 'Life',
      'Life 1st', 'Life Business', 'Life Business 1st', 'Life Plus', 'Lounge', 'Match', 'MATCH',
      'Match 2', 'Match Allstar', 'Mayflower', 'Miami', 'Pack', 'Pink Floyd', 'Quartet', 'R',
      'R 20 ans', 'R32', 'R-Line', 'R-Line 1st', 'R-Line Edition', 'Rolling Stones', 'S',
      'Sound', 'S Pack', 'Sport', 'Sportline', 'Sport Plus', 'Style', 'Style 1st', 'Trend',
      'Trendline', 'Trendline Business', 'Trend Pack', 'United', 'VR6', 'VW Edition', 'Wembley',
      'Wembley Plus',
    ],
  },
};
